name: PHP Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml
          tools: php-cs-fixer

      - name: Check syntax with PHP Lint
        run: find . -name '*.php' -exec php -l {} \;

      - name: Install PHP CodeSniffer and PHPCBF
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar

      - name: Check coding standards with PHP_CodeSniffer
        run: php phpcs.phar --standard=PSR12 ./

      - name: Fix coding standards with PHP_CodeSniffer
        run: php phpcbf.phar --standard=PSR12 ./
